[project]
name = "pygrader"
version = "1.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pylint>=4.0.2",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "types-requests>=2.32.4.20250913",
]

[tool.complexipy]
paths = ["grader", "tests", "desktop", "web"]
max-complexity-allowed = 10
quiet = false
sort = "asc"
details = "low"

[tool.complexipy.output]
json = true

[dependency-groups]
dev = [
    "complexipy>=4.2.0",
    "flake8>=7.3.0",
    "mypy>=1.18.2",
]
