name: pygrader pull request checks

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Install just
        run: sudo apt install just

      - name: Lint code
        run: just lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Install just
        run: sudo apt install just

      - name: Run the unit tests
        run: just unit_tests

      - name: Run the functional tests
        run: just functional_tests

  changelog-and-version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if CHANGELOG.md is updated
        run: |
          git fetch origin main:main
          if git diff --name-only origin/main...HEAD | grep -q "CHANGELOG.md"; then
            echo "✓ CHANGELOG.md has been updated"
          else
            echo "✗ CHANGELOG.md has not been updated"
            exit 1
          fi
        shell: bash

      - name: Check if version is changed
        run: |
          git fetch origin main:main
          if git diff origin/main...HEAD pyproject.toml | grep -q "^[+-]version = "; then
            echo "✓ Version in pyproject.toml has been changed"
          else
            echo "✗ Version in pyproject.toml has not been changed"
            exit 1
          fi
        shell: bash